trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
variables:
  myName: Rithwik
 
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo "Build started 🚀"
        echo "User: $(whoami)"
        echo "Date: $(date)"
        echo "Hello $(myName)" > report.txt
        cat report.txt
      displayName: Build + System Info
 
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'report.txt'
        artifactName: 'build-report'
      displayName: Publish Artifact
 
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: |
        echo "Running tests ✅"
        echo "Simulating test..."
      displayName: Test Stage
 
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: |
        echo "Deploying 🚀"
        echo "Pipeline ID: $(Build.BuildId)"
      displayName: Deploy Stage